### ISSUE TITLE
Software

### ISSUE THREAD

**Issue by antAmaine** [COS420-Fall24/TeamH#45]
Create issues based on the Software  section of the grading rubric in the deliverable description in the D1 assignment doc in the drive, then add them to deliverable 1 milestone, TeamH Kanban project, with tagged as Software

The file is stored in ~/D1/D1 assignment

Link: [D1 assignment](https://docs.google.com/document/d/1S8Ntgvo2u2E7zfQvC7joMyBZX04KkDe9F1zyDs4oYpE/edit?usp=sharing)

**Comment by Linkaboy** [comment]
Tasks were created. Just waiting on further updates

**Comment by Linkaboy** [comment]
The implementation should have been started. 
If there is no code/HTML/scripts in Github, this part will be graded as 0.
Setting up the build environments and the necessary dependencies.  
You do not need to have any significant progress on developing your application. Focus on setting up the build environment.You can use create-react-app or otherwise create your project structure.


Your README file should detail the installation and build process for your application. Make sure it works on each person’s machine.
Submit screenshot(s) or a single video showing the app running on each person’s machine 
If there is nothing, deduct -5 points.
