### ISSUE TITLE
Create Kanban board

### ISSUE THREAD

**Issue by obedappiah** [COS420-Fall24/TeamH#53]
Kanban (/15)
Kanban board should be created and shared with the group (on your issue/task management platform e.g. Github Issues + Github Projects, Jetbrains Space, etc)
Kanban board should show progress and activity (i.e. be updated and used).
If no progress is shown, the grade for this part will be 0.
The Kanban must have quality checking tasks and tasks for integrating the deliverables together, with enough time to assign tasks to fix that before submission. That integration and quality checking work should be distributed and also done by people who are not the PM, otherwise it’s too much work for the PM. If this is missing, -3 points.
There should be 15-30 tasks for this Deliverable and any revisions for the previous Deliverable. Each task should be small.

Template: [Greg's Template](https://github.com/orgs/COS420-Fall24/projects/15/views/1l)

**Comment by antAmaine** [comment]
Kanban (/15) 
Kanban board should be created and shared with the group (on your issue/task management platform e.g. Github Issues + Github Projects, Jetbrains Space, etc)
Kanban board should show progress and activity (i.e. be updated and used).
If no progress is shown, the grade for this part will be 0.
The Kanban must have quality checking tasks and tasks for integrating the deliverables together, with enough time to assign tasks to fix that before submission. That integration and quality checking work should be distributed and also done by people who are not the PM, otherwise it’s too much work for the PM. If this is missing, -3 points.
There should be 15-30 tasks for this Deliverable and any revisions for the previous Deliverable. Each task should be small.

Template: [https://github.com/orgs/COS420-Fall24/projects/15/views/1}
